firetail:
  apikey: "set-your-ft-api-key-here"
  url: "https://your.sandbox.firetail.app"

logging:
  level:
    root: debug
    io:
      firetail: debug
    com.example.demo: debug
    javax: error
    java: debug
    #java.net: debug
    sun: error
    netflix: error
    jdk: error
    org:
      springframework: error
      apache: error


  firetail:
    enabled: true


springdoc:
    api-docs:
      path: /api-docs
